### ISSUE TITLE
hmvc modules form_validation session

### ISSUE THREAD

**Issue by abin2011** [jenssegers/codeigniter-hmvc-modules#15]
Codeigniter version: 2.2.0
HMVC:codeigniter-hmvc-modules
The problem:
the  form_validation set_value() function is not work!
My code :
 <?php echo $this->load->controller('header',NULL,FALSE);?>
  <form id="form_contact" action="<?=site_url('contact/posts')?>" method="post" class="form-inline">
    <div class="grid-100 grid-parent">
      <div class="grid-50"><label>Name</label>
        input type="text" name="name" value="<?php echo set_value('name')?>" 
      </div>
      <div class="grid-50"><label>Phone</label>
        input type="text" name="phone" value="<?php echo set_value('phone')?>" 
      </div>
    </div>
   </form>
  <?php echo $this->load->controller('footer',NULL,FALSE);?>
 The name and phone are Required
If I just fill in the name wrong before can not obtain the value
config/autoload.php $autoload['libraries'] = array('database','session','form_validation');
plese help me!

**Comment by abin2011** [comment]
call jens

**Comment by Patroklo** [comment]
Why are you using a $this->load->controller? It's really neccesary? You are breaking the CMV paradigm there. Depending of which version of CI you have (can't remember right now if 2.2 was one of them), the problem should be there, because you are loading two different controllers, and also loading all the autoload libraries two times, so the set_value and a lot more methods won't work as you expect.

If you want to use this->controller as a loader for zones of your views, you should try the template library that jens has that uses views instead of controllers. Or use the views yourself. Try that (not using the controller loading) and let us know!

**Comment by abin2011** [comment]
<?php echo $this->load->controller('header',NULL,FALSE);?> 
This problem as it appears on the controller

**Comment by Patroklo** [comment]
Don't understand what you are trying to say there, mate XD

**Comment by abin2011** [comment]
I'm sorry,My English is so bad!
 I mean to say:
    this code in the controller it's same not work!
my code:

![qq 20140912153131](https://cloud.githubusercontent.com/assets/1227434/4246716/10acab8c-3a4f-11e4-9526-c821e0c7708c.jpg)

![qq 20140912153215](https://cloud.githubusercontent.com/assets/1227434/4246718/17a58b3e-3a4f-11e4-91dc-49ffaa0a971e.jpg)

**Comment by Patroklo** [comment]
Now comment the $this->load->controller line, don't use it, don't use the header, just for trial, and launch the form and tell if withouth the $this->load->controller it works fine.

**Comment by abin2011** [comment]
if don't use it  
the set_value('name') is work!
but I need to write like this.
Because header footer are common!

**Comment by abin2011** [comment]
like this
https://github.com/Bigwebmaster/codeigniter-modular-extensions-hmvc
When using form validation with MX you will need to extend the CI_Form_validation class as shown below,

:::php
<?php
/*\* application/libraries/MY_Form_validation **/ 
class MY_Form_validation extends CI_Form_validation 
{
    public $CI;
}
before assigning the current controller as the $CI variable to the form_validation library. This will allow your callback methods to function properly. (This has been discussed on the CI forums also).

:::php
<?php
class Xyz extends MX_Controller 
{
    function __construct()
    {
        parent::__construct();

```
    $this->load->library('form_validation');
    $this->form_validation->CI =& $this;
}
```

}

**Comment by Patroklo** [comment]
Ok, the problem, as I have said, it's that, when you use $this->load->controller, you initialize again all the libraries that are in the autoload. SO, you lose all previous data in EVERY library, helper, model, etc...

I suggest that you use a template system, if you are using common views in the generation of the web, like the one that jenssegers has in https://github.com/jenssegers/codeigniter-template-library (I have used it and I liked a lot, really!). OR you can change the $this->load->controler to a $this->load->(anything) (I suggest a view). 

I don't know what you do in the header controller, but you should never use controller loading (being able to do something doesn't mean that it's a good idea doing that).

If I were doing a project, I'll use the template system OR a view to load the header and footers. Don't know if that's possible in yours.

**Comment by Patroklo** [comment]
About the other hvmc library, I personally have used it in the past, but didn't like it much. I think that the jes module it's more elegant, faster and gives less problems.

About the use of $this in the form_validation in this module, I haven't used it because it's not neccesary, I don't really know if that would solve your problem, but it doesn't seem plausible.

**Comment by Patroklo** [comment]
Whatever you do, if it finally works, please tell and close the issue if you can. If not, I'll try to help you

**Comment by abin2011** [comment]
Sorry,
我在想怎么样告诉你我的想法和理解.
我用中文可以吗?

**Comment by Patroklo** [comment]
As long as google translate can do it's work, yes XD

**Comment by abin2011** [comment]
这个 Codeigniter  HMVC 扩展
难道不能在一个Controller里面调用另外一个Controller吗?
我看那实例代码上是可以在Controller中实现$this->load->controller('blogs/random', array('specials'));调用的.
那既然可以,本身应该不能影响form_validation的工作啊.
我明白你说的$this->load->controller 等于重新初始化了所有library, helper, model, etc...
但是 我现在想的是 能不能预留一个扩展或者变量 让我能继承之前的 form_validation

**Comment by abin2011** [comment]
谢谢你回复我,Patroklo ,thank you!

你是怎么样实现验证的呢?
如果你用HMVC,前提是,你也在Controller中调用了其他Controller.

**Comment by Patroklo** [comment]
As I have said, being able to do something doesn't mean that you should do it. In this case you have to change the $this->load->controller into something else and everything will work again. I'm trying to think of a way of using the loading controller method whitout that problem and whitout extending the controller class, but I can't think of one right now.

**Comment by abin2011** [comment]
我采用HVMC主要的原因是我想分开每一个模块,同时在我需要的时候我能组装起来
比如我现在的:样式mvc,菜单mvc,导航mvc,状态栏mvc  他们组装起来就是一个共同的 header
同时我可以在后台控制 样式,菜单,导航.
现在 form_validation 的 set_value('name') 这样不能工作
但是我仍然可以在 Controller中写
$data['name']=$this->input->post('name')
然后在Views中写
input type="text" name="name" value="<?php echo set_value('name',isset($name)?$name:'')?>"  
加个默认值来实现,set_value('Field',$default) 通过$default来实现

但是这样无形中我要写多很多$data['name']=$this->input->post('name')...
所以我就希望能不能 预留一个扩展,然后让form_validation 自行扩展.

**Comment by Patroklo** [comment]
You can extend the class controller in order to only load libraries once. Then you will be able to use this->load->controller without a problem.

**Comment by Patroklo** [comment]
Something like the __construct method of this class https://github.com/Patroklo/codeigniter-mashup-cooperative/blob/master/application/core/AJAX_Controller.php

**Comment by abin2011** [comment]
OK,I try it,
thank you! you are vary nice!

**Comment by Patroklo** [comment]
If you have any problem just aks here.

**Comment by abin2011** [comment]
Hi, Patroklo 
set_value() 方法不能获取值的问题 我通过在Controller $this->data['name']=$this->input->post('name');处理了

但是 发现 session的闪出数据 进行提示的时候 又不行了
$this->session->set_flashdata('item', 'value');
this  $this->session->flashdata('item'); is not working
HMVC 真是丢失了很多librarie
