### ISSUE TITLE
Views not displaying

### ISSUE THREAD

**Issue by dollardad** [jenssegers/codeigniter-hmvc-modules#3]
Views are not displaying except in the default controller

application/
                 modules/
                               welcome/
                                              controllers/
                                                               welcome.php
                                              views/
                                                        welcome_message.php
                               admin/
                                         controllers/
                                                          admin.php
                                         views/
                                                  admin_message.php

call $this->load->view('admin_message') from the admin controller will not display from the views folder inside admin only from the main application/views folder

call $this->load->view('welcome_message') from the welcome controller will display view that is in the welcome module views folder 

Would be great to call partials from the module's own view folder

**Comment by jenssegers** [comment]
This should not be the case. Will look into this.

**Comment by jenssegers** [comment]
Was this fixed with the last commit?

**Comment by dollardad** [comment]
Not that I am aware of all though to be fair the last few projects I've been using PyroCMS
