### ISSUE TITLE
hi jenssegers

### ISSUE THREAD

**Issue by abin2011** [jenssegers/codeigniter-hmvc-modules#6]
I use this codeigniter your extension 
Found the session of flashdata not work
code:
      $result=$this->data_mdl->edit_data($data,$edit_id);
      $msg = $result > 0?'is ok!':'error';
      $notify = $result > 0?'success':'error';
      // $this->nsession->set_flashdata($notify, $msg);
      // $this->nsession->keep_flashdata($notify);
      $this->session->set_flashdata($notify, $msg);
      $this->session->keep_flashdata($notify);
      var_dump($this->session->all_userdata());

result:
array(7) {
  ["session_id"]=&gt;
  string(32) "774a709dff1073976144c8976902f1be"
  ["ip_address"]=&gt;
  string(9) "127.0.0.1"
  ["user_agent"]=&gt;
  string(72) "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0"
  ["last_activity"]=&gt;
  int(1393646597)
  ["user_data"]=&gt;
  string(0) ""
  ["flash:old:success"]=&gt;
  bool(false)
  ["flash:new:success"]=&gt;
  bool(false)
}  

flash:old:success return FALSE
how to modify code?

**Comment by jenssegers** [comment]
This repository is no longer under active development.
