### ISSUE TITLE
Add Third Controller Level In Router

### ISSUE THREAD

**Issue by tasmanwebsolutions** [jenssegers/codeigniter-hmvc-modules#7]
Hi I would like to know if it is possible to add in the router and loader a third level for controllers. Because at the moment can only get one level.

Example: 
Can on get controller like below.
folder/controllers.php

Would like to be able to get
folder/folder/controller.php

And also can I change names of the $module and location on my one.
I am making template system that if open source on git hub my new version coming soon.

**Comment by jenssegers** [comment]
This repository is no longer under active development.

**Comment by tasmanwebsolutions** [comment]
Can I add stuff to it then. If I can get my developer to make second level. And can I rename modules and change location

**Comment by tasmanwebsolutions** [comment]
I can get my developer to look after it if no longer active development.
