### ISSUE TITLE
Just Quick Question

### ISSUE THREAD

**Issue by tasmanwebsolutions** [jenssegers/codeigniter-hmvc-modules#8]
If it is not in active development could I get my developer to look after it. And add a couple of things.

Tried finding your email did not want to make issue on here.

**Comment by jenssegers** [comment]
Pull requests are always welcome.

**Comment by tasmanwebsolutions** [comment]
And can I rename module and change location on my copy. I will get my developer to see if he can make second level. Its just easier for my template system.

**Comment by tasmanwebsolutions** [comment]
How to load in routes if controller is in modules/catalog/controller/common and what way do you load views

**Comment by tasmanwebsolutions** [comment]
I have worked it out. Just getting quote of my developer to find out how to get second level. Once he has done it in next couple weeks will do a pull request.
