### ISSUE TITLE
Sub Directory File For HMVC

### ISSUE THREAD

**Issue by tasmanwebsolutions** [jenssegers/codeigniter-hmvc-modules#9]
Hi Matthew here. I have found some code that I have been putting together. To make your HMVC Codeigniter be able to have sub directories but have a couple of bugs in it. 

If you have got time could you look at it?

If you could fix it the you can add it to your hmvc. Its only couple minor fixes I think. It would be a good edition to it if can make it work.

**Comment by jenssegers** [comment]
Sorry, but I don't use codeigniter anymore.

**Comment by tasmanwebsolutions** [comment]
If you don't use codeigniter any more would you like to transfer it over to me and my developer and i can look after it on git hub I we use codeigniter a lot.

**Comment by jenssegers** [comment]
It's open source. You can fork and modify it.

**Comment by tasmanwebsolutions** [comment]
You want me to keep your MIT License on there. Just thought I would check. I am happy either way,
